# ***Numpy***

In [6]:
import numpy as np


In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])


In [8]:
arr_add = arr + 2      
arr_sub = arr - 1      
arr_mul = arr * 2      
arr_div = arr / 2      

In [9]:
print(arr_add)

[[3 4 5]
 [6 7 8]]


In [10]:

print(arr_sub)

[[0 1 2]
 [3 4 5]]


In [11]:
print(arr_mul)


[[ 2  4  6]
 [ 8 10 12]]


In [12]:
print(arr_div)

[[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [13]:
#Answer 2

In [14]:
element = arr[1, 2]           # Accesses element at row 2, column 3
subset = arr[:, 1:3]

In [15]:
element

6

In [16]:
subset

array([[2, 3],
       [5, 6]])

In [17]:
#Answer 3

In [18]:
reshaped = arr.reshape(3, 2)  
transposed = arr.T           

In [19]:
reshaped


array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
transposed

array([[1, 4],
       [2, 5],
       [3, 6]])

In [21]:
#Answer 4

In [22]:
mean_value = np.mean(arr)     
median_value = np.median(arr) 
std_value = np.std(arr)       
var_value = np.var(arr)

In [23]:
mean_value


3.5

In [24]:
median_value

3.5

In [25]:
std_value

1.707825127659933

In [26]:
var_value

2.9166666666666665

In [27]:
#Answer 5

In [28]:
arr_int = np.array([1, 2, 3], dtype=int)   
arr_float = np.array([1.1, 2.2, 3.3], dtype=float)  
arr_bool = np.array([True, False, True], dtype=bool) 
arr_str = np.array(["a", "b", "c"], dtype=str)

In [29]:
#Answer 6

In [30]:
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
concatenated = np.concatenate((arr, arr2), axis=0) 


In [31]:
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [32]:
concatenated

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
#Answer 7

In [34]:

sorted_arr_asc = np.sort(arr, axis=None)  
sorted_arr_desc = np.sort(arr, axis=None)[::-1]

In [35]:
sorted_arr_asc

array([1, 2, 3, 4, 5, 6])

In [36]:
sorted_arr_desc

array([6, 5, 4, 3, 2, 1])


# ***Pandas***

In [38]:
import pandas as pd

In [39]:
df_csv = pd.read_csv('StudentPerformanceFactors.csv') 

In [40]:
df_csv

Hours_Studied  Attendance Parental_Involvement Access_to_Resources  \
0                23          84                  Low                High   
1                19          64                  Low              Medium   
2                24          98               Medium              Medium   
3                29          89                  Low              Medium   
4                19          92               Medium              Medium   
...             ...         ...                  ...                 ...   
6602             25          69                 High              Medium   
6603             23          76                 High              Medium   
6604             20          90               Medium                 Low   
6605             10          86                 High                High   
6606             15          67               Medium                 Low   

     Extracurricular_Activities  Sleep_Hours  Previous_Scores  \
0                            No            7               73   
1                            No            8               59   
2                           Yes            7               91   
3                           Yes            8               98   
4                           Yes            6               65   
...                         ...          ...              ...   
6602                         No            7               76   
6603                         No            8               81   
6604                        Yes            6               65   
6605                        Yes            6               91   
6606                        Yes            9               94   

     Motivation_Level Internet_Access  Tutoring_Sessions Family_Income  \
0                 Low             Yes                  0           Low   
1                 Low             Yes                  2        Medium   
2              Medium             Yes                  2        Medium   
3              Medium             Yes                  1        Medium   
4              Medium             Yes                  3        Medium   
...               ...             ...                ...           ...   
6602           Medium             Yes                  1          High   
6603           Medium             Yes                  3           Low   
6604              Low             Yes                  3           Low   
6605             High             Yes                  2           Low   
6606           Medium             Yes                  0        Medium   

     Teacher_Quality School_Type Peer_Influence  Physical_Activity  \
0             Medium      Public       Positive                  3   
1             Medium      Public       Negative                  4   
2             Medium      Public        Neutral                  4   
3             Medium      Public       Negative                  4   
4               High      Public        Neutral                  4   
...              ...         ...            ...                ...   
6602          Medium      Public       Positive                  2   
6603            High      Public       Positive                  2   
6604          Medium      Public       Negative                  2   
6605          Medium     Private       Positive                  3   
6606          Medium      Public       Positive                  4   

     Learning_Disabilities Parental_Education_Level Distance_from_Home  \
0                       No              High School               Near   
1                       No                  College           Moderate   
2                       No             Postgraduate               Near   
3                       No              High School           Moderate   
4                       No                  College               Near   
...                    ...                      ...                ...   
6602                    No              High School             

In [41]:
#Answer 2

In [42]:
shape = df_csv.shape                  
dtypes = df_csv.dtypes                
missing_values = df_csv.isnull().sum() 

In [43]:
shape

(6607, 20)

In [44]:
dtypes

Hours_Studied                  int64
Attendance                     int64
Parental_Involvement          object
Access_to_Resources           object
Extracurricular_Activities    object
Sleep_Hours                    int64
Previous_Scores                int64
Motivation_Level              object
Internet_Access               object
Tutoring_Sessions              int64
Family_Income                 object
Teacher_Quality               object
School_Type                   object
Peer_Influence                object
Physical_Activity              int64
Learning_Disabilities         object
Parental_Education_Level      object
Distance_from_Home            object
Gender                        object
Exam_Score                     int64
dtype: object

In [45]:
missing_values

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

In [46]:
#Answer 3

In [47]:
summary = df_csv.describe() 

In [48]:
summary

Hours_Studied   Attendance  Sleep_Hours  Previous_Scores  \
count    6607.000000  6607.000000   6607.00000      6607.000000   
mean       19.975329    79.977448      7.02906        75.070531   
std         5.990594    11.547475      1.46812        14.399784   
min         1.000000    60.000000      4.00000        50.000000   
25%        16.000000    70.000000      6.00000        63.000000   
50%        20.000000    80.000000      7.00000        75.000000   
75%        24.000000    90.000000      8.00000        88.000000   
max        44.000000   100.000000     10.00000       100.000000   

       Tutoring_Sessions  Physical_Activity   Exam_Score  
count        6607.000000        6607.000000  6607.000000  
mean            1.493719           2.967610    67.235659  
std             1.230570           1.031231     3.890456  
min             0.000000           0.000000    55.000000  
25%             1.000000           2.000000    65.000000  
50%             1.000000           3.000000    67.000000  
75%             2.000000           4.000000    69.000000  
max             8.000000           6.000000   101.000000

In [49]:
#Answer 4

In [105]:
specific_columns = df_csv[['Hours_Studied', 'Sleep_Hours']]


In [107]:
specific_columns

Hours_Studied  Sleep_Hours
0                23            7
1                19            8
2                24            7
3                29            8
4                19            6
...             ...          ...
6602             25            7
6603             23            8
6604             20            6
6605             10            6
6606             15            9

[6607 rows x 2 columns]

In [109]:
specific_rows = df_csv[df_csv['Hours_Studied'] > 10]

In [111]:
specific_rows

Hours_Studied  Attendance Parental_Involvement Access_to_Resources  \
0                23          84                  Low                High   
1                19          64                  Low              Medium   
2                24          98               Medium              Medium   
3                29          89                  Low              Medium   
4                19          92               Medium              Medium   
...             ...         ...                  ...                 ...   
6601             20          83               Medium                 Low   
6602             25          69                 High              Medium   
6603             23          76                 High              Medium   
6604             20          90               Medium                 Low   
6606             15          67               Medium                 Low   

     Extracurricular_Activities  Sleep_Hours  Previous_Scores  \
0                            No            7               73   
1                            No            8               59   
2                           Yes            7               91   
3                           Yes            8               98   
4                           Yes            6               65   
...                         ...          ...              ...   
6601                         No            6               51   
6602                         No            7               76   
6603                         No            8               81   
6604                        Yes            6               65   
6606                        Yes            9               94   

     Motivation_Level Internet_Access  Tutoring_Sessions Family_Income  \
0                 Low             Yes                  0           Low   
1                 Low             Yes                  2        Medium   
2              Medium             Yes                  2        Medium   
3              Medium             Yes                  1        Medium   
4              Medium             Yes                  3        Medium   
...               ...             ...                ...           ...   
6601              Low             Yes                  2        Medium   
6602           Medium             Yes                  1          High   
6603           Medium             Yes                  3           Low   
6604              Low             Yes                  3           Low   
6606           Medium             Yes                  0        Medium   

     Teacher_Quality School_Type Peer_Influence  Physical_Activity  \
0             Medium      Public       Positive                  3   
1             Medium      Public       Negative                  4   
2             Medium      Public        Neutral                  4   
3             Medium      Public       Negative                  4   
4               High      Public        Neutral                  4   
...              ...         ...            ...                ...   
6601          Medium      Public        Neutral                  4   
6602          Medium      Public       Positive                  2   
6603            High      Public       Positive                  2   
6604          Medium      Public       Negative                  2   
6606          Medium      Public       Positive                  4   

     Learning_Disabilities Parental_Education_Level Distance_from_Home  \
0                       No              High School               Near   
1                       No                  College           Moderate   
2                       No             Postgraduate               Near   
3                       No              High School           Moderate   
4                       No                  College               Near   
...                    ...                      ...                ...   
6601                    No              High School           Mo

In [113]:
specific_rows = df_csv[df_csv['Sleep_Hours'] > 10]

In [115]:
specific_rows

Empty DataFrame
Columns: [Hours_Studied, Attendance, Parental_Involvement, Access_to_Resources, Extracurricular_Activities, Sleep_Hours, Previous_Scores, Motivation_Level, Internet_Access, Tutoring_Sessions, Family_Income, Teacher_Quality, School_Type, Peer_Influence, Physical_Activity, Learning_Disabilities, Parental_Education_Level, Distance_from_Home, Gender, Exam_Score]
Index: []

In [117]:
specific_rows = df_csv[df_csv['Attendance'] > 70]

In [119]:
specific_rows

Hours_Studied  Attendance Parental_Involvement Access_to_Resources  \
0                23          84                  Low                High   
2                24          98               Medium              Medium   
3                29          89                  Low              Medium   
4                19          92               Medium              Medium   
5                19          88               Medium              Medium   
...             ...         ...                  ...                 ...   
6600             12          98               Medium                 Low   
6601             20          83               Medium                 Low   
6603             23          76                 High              Medium   
6604             20          90               Medium                 Low   
6605             10          86                 High                High   

     Extracurricular_Activities  Sleep_Hours  Previous_Scores  \
0                            No            7               73   
2                           Yes            7               91   
3                           Yes            8               98   
4                           Yes            6               65   
5                           Yes            8               89   
...                         ...          ...              ...   
6600                        Yes            4               54   
6601                         No            6               51   
6603                         No            8               81   
6604                        Yes            6               65   
6605                        Yes            6               91   

     Motivation_Level Internet_Access  Tutoring_Sessions Family_Income  \
0                 Low             Yes                  0           Low   
2              Medium             Yes                  2        Medium   
3              Medium             Yes                  1        Medium   
4              Medium             Yes                  3        Medium   
5              Medium             Yes                  3        Medium   
...               ...             ...                ...           ...   
6600           Medium             Yes                  2        Medium   
6601              Low             Yes                  2        Medium   
6603           Medium             Yes                  3           Low   
6604              Low             Yes                  3           Low   
6605             High             Yes                  2           Low   

     Teacher_Quality School_Type Peer_Influence  Physical_Activity  \
0             Medium      Public       Positive                  3   
2             Medium      Public        Neutral                  4   
3             Medium      Public       Negative                  4   
4               High      Public        Neutral                  4   
5             Medium      Public       Positive                  3   
...              ...         ...            ...                ...   
6600            High     Private        Neutral                  3   
6601          Medium      Public        Neutral                  4   
6603            High      Public       Positive                  2   
6604          Medium      Public       Negative                  2   
6605          Medium     Private       Positive                  3   

     Learning_Disabilities Parental_Education_Level Distance_from_Home  \
0                       No              High School               Near   
2                       No             Postgraduate               Near   
3                       No              High School           Moderate   
4                       No                  College               Near   
5                       No             Postgraduate               Near   
...                    ...                      ...                ...   
6600                    No              High School             